// <auto-generated />
using CodeLouCapstone.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeLouCapstone.Api.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241111172847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CodeLouCapstone.Shared.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            CardName = "Plains"
                        },
                        new
                        {
                            CardId = 2,
                            CardName = "Island"
                        },
                        new
                        {
                            CardId = 3,
                            CardName = "Swamp"
                        },
                        new
                        {
                            CardId = 4,
                            CardName = "Mountain"
                        },
                        new
                        {
                            CardId = 5,
                            CardName = "Forest"
                        },
                        new
                        {
                            CardId = 6,
                            CardName = "Abandoned Campground"
                        },
                        new
                        {
                            CardId = 7,
                            CardName = "Abhorrent Oculus"
                        },
                        new
                        {
                            CardId = 8,
                            CardName = "Abrade"
                        },
                        new
                        {
                            CardId = 9,
                            CardName = "Abraded Bluffs"
                        },
                        new
                        {
                            CardId = 10,
                            CardName = "Absolving Lammasu"
                        },
                        new
                        {
                            CardId = 11,
                            CardName = "Abuelo, Ancestral Echo"
                        },
                        new
                        {
                            CardId = 12,
                            CardName = "Abuelo's Awakening"
                        },
                        new
                        {
                            CardId = 13,
                            CardName = "Abyssal Gorestalker"
                        },
                        new
                        {
                            CardId = 14,
                            CardName = "Academy Loremaster"
                        },
                        new
                        {
                            CardId = 15,
                            CardName = "Academy Wall"
                        },
                        new
                        {
                            CardId = 16,
                            CardName = "Aclazotz, Deepest Betrayal"
                        },
                        new
                        {
                            CardId = 17,
                            CardName = "Acolyte of Aclazotz"
                        },
                        new
                        {
                            CardId = 18,
                            CardName = "Acrobatic Cheerleader"
                        },
                        new
                        {
                            CardId = 19,
                            CardName = "Acrobatic Leap"
                        },
                        new
                        {
                            CardId = 20,
                            CardName = "Adaptive Gemguard"
                        },
                        new
                        {
                            CardId = 21,
                            CardName = "Adaptive Sporesinger"
                        },
                        new
                        {
                            CardId = 22,
                            CardName = "Adakar Wastes"
                        },
                        new
                        {
                            CardId = 23,
                            CardName = "Aerial Boost"
                        },
                        new
                        {
                            CardId = 24,
                            CardName = "Aeronaut Cavalry"
                        },
                        new
                        {
                            CardId = 25,
                            CardName = "Aeronaut's Wings"
                        },
                        new
                        {
                            CardId = 26,
                            CardName = "Aetherblade Agent"
                        },
                        new
                        {
                            CardId = 27,
                            CardName = "Aether Channeler"
                        },
                        new
                        {
                            CardId = 28,
                            CardName = "Aftermath Analyst"
                        },
                        new
                        {
                            CardId = 29,
                            CardName = "Against All Odds"
                        },
                        new
                        {
                            CardId = 30,
                            CardName = "Agate Assault"
                        },
                        new
                        {
                            CardId = 31,
                            CardName = "Agate-Blade Assassin"
                        },
                        new
                        {
                            CardId = 32,
                            CardName = "Agatha of the Vile Cauldron"
                        },
                        new
                        {
                            CardId = 33,
                            CardName = "Agatha's Champion"
                        },
                        new
                        {
                            CardId = 34,
                            CardName = "Agatha's Soul Cauldron"
                        },
                        new
                        {
                            CardId = 35,
                            CardName = "Agency Coroner"
                        },
                        new
                        {
                            CardId = 36,
                            CardName = "Agency Outfitter"
                        },
                        new
                        {
                            CardId = 37,
                            CardName = "Aggressive Sabotage"
                        },
                        new
                        {
                            CardId = 38,
                            CardName = "Agrus Kos, Spirit of Justice"
                        },
                        new
                        {
                            CardId = 39,
                            CardName = "Airlift Chaplain"
                        },
                        new
                        {
                            CardId = 40,
                            CardName = "Air Marshal"
                        },
                        new
                        {
                            CardId = 41,
                            CardName = "Airtight Alibi"
                        },
                        new
                        {
                            CardId = 42,
                            CardName = "Ajani, Sleeper Agent"
                        },
                        new
                        {
                            CardId = 43,
                            CardName = "Akal Pakal, First Among Equals"
                        },
                        new
                        {
                            CardId = 44,
                            CardName = "Akawalli, the Seething Tower"
                        },
                        new
                        {
                            CardId = 45,
                            CardName = "A Killer Among Us"
                        },
                        new
                        {
                            CardId = 46,
                            CardName = "Akki Scrapchomper"
                        },
                        new
                        {
                            CardId = 47,
                            CardName = "Akul the Unrepentant"
                        },
                        new
                        {
                            CardId = 48,
                            CardName = "Alabaster Host Intercessor"
                        },
                        new
                        {
                            CardId = 49,
                            CardName = "Alabaster Host Sanctifier"
                        },
                        new
                        {
                            CardId = 50,
                            CardName = "Alania, Divergent Storm"
                        },
                        new
                        {
                            CardId = 51,
                            CardName = "Alania's Pathmaker"
                        },
                        new
                        {
                            CardId = 52,
                            CardName = "Alley Assailant"
                        },
                        new
                        {
                            CardId = 53,
                            CardName = "Alloy Animist"
                        },
                        new
                        {
                            CardId = 54,
                            CardName = "All Will Be One"
                        },
                        new
                        {
                            CardId = 55,
                            CardName = "Aloe Alchemist"
                        },
                        new
                        {
                            CardId = 56,
                            CardName = "Alquist Proft, Master Sleuth"
                        },
                        new
                        {
                            CardId = 57,
                            CardName = "Altanak, the Thrice-Called"
                        },
                        new
                        {
                            CardId = 58,
                            CardName = "Amalia Benavides Aguirre"
                        },
                        new
                        {
                            CardId = 59,
                            CardName = "Ambulatory Edifice"
                        },
                        new
                        {
                            CardId = 60,
                            CardName = "Ambush Gigapede"
                        },
                        new
                        {
                            CardId = 61,
                            CardName = "Ambush Paratrooper"
                        },
                        new
                        {
                            CardId = 62,
                            CardName = "Analyze the Pollen"
                        },
                        new
                        {
                            CardId = 63,
                            CardName = "Ancestors' Aid"
                        },
                        new
                        {
                            CardId = 64,
                            CardName = "Ancestral Reminiscence"
                        },
                        new
                        {
                            CardId = 65,
                            CardName = "Ancient Cornucopia"
                        },
                        new
                        {
                            CardId = 66,
                            CardName = "Ancient Imperiosaur"
                        },
                        new
                        {
                            CardId = 67,
                            CardName = "Angelic Intervention"
                        },
                        new
                        {
                            CardId = 68,
                            CardName = "Animist's Might"
                        },
                        new
                        {
                            CardId = 69,
                            CardName = "Anim Pakal, Thousandth Moon"
                        },
                        new
                        {
                            CardId = 70,
                            CardName = "Ankle Biter"
                        },
                        new
                        {
                            CardId = 71,
                            CardName = "Annex Sentry"
                        },
                        new
                        {
                            CardId = 72,
                            CardName = "Annie Flash, the Veteran"
                        },
                        new
                        {
                            CardId = 73,
                            CardName = "Annie Joins Up"
                        },
                        new
                        {
                            CardId = 74,
                            CardName = "Annihilating Glare"
                        },
                        new
                        {
                            CardId = 75,
                            CardName = "Anointed Peacekeeper"
                        },
                        new
                        {
                            CardId = 76,
                            CardName = "Anoint with Affliction"
                        },
                        new
                        {
                            CardId = 77,
                            CardName = "Another Chance"
                        },
                        new
                        {
                            CardId = 78,
                            CardName = "Another Round"
                        },
                        new
                        {
                            CardId = 79,
                            CardName = "Anthropede"
                        },
                        new
                        {
                            CardId = 80,
                            CardName = "Anzrag's Rampage"
                        },
                        new
                        {
                            CardId = 81,
                            CardName = "Anzrag, the Quake-Mole"
                        },
                        new
                        {
                            CardId = 82,
                            CardName = "Apostle of Invasion"
                        },
                        new
                        {
                            CardId = 83,
                            CardName = "Appendage Amalgam"
                        },
                        new
                        {
                            CardId = 84,
                            CardName = "Aquatic Alchemist"
                        },
                        new
                        {
                            CardId = 85,
                            CardName = "Arabella, Abandoned Doll"
                        },
                        new
                        {
                            CardId = 86,
                            CardName = "Arachnoid Adaptation"
                        });
                });

            modelBuilder.Entity("CodeLouCapstone.Shared.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            DeckId = 1,
                            Cards = "[\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\",\"Plains\"]",
                            DeckName = "Sample Deck"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
